build:
  version: 2016-03-14
  steps:
    builder:
      name: builder
      dockerfile: Dockerfile.builder
    toolkit:
      name: zealic/toolkit
      dockerfile: Dockerfile
      depends_on:
        - builder
